name: pkgdown site
on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 03 * * *'
#      image: bioconductor/bioconductor_docker:devel
jobs:
  build-pkgdown-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    container:
      image: rockerdev/geospatial
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      # cache package dependencies
      - name: Get package dependency cache
        uses: actions/cache@v1
        env:
          cache-name: r-site-library-bioc-devel-docker
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('DESCRIPTION') }}


      - name: Install package and dependencies
        run: |
          Rscript -e "install.packages('BiocManager')"
          Rscript -e "install.packages(c('pkgbuild','prettyunits'))"
          Rscript -e "devtools::install('.', dependencies=TRUE, repos = BiocManager::repositories())"

      - name: Build pkgdown
        env:
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site(".")'

      # deploy needs rsync? Seems so.

      - name: Install deploy dependencies
        run: |
          apt-get update
          apt-get -y install rsync

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
